### PR TITLE
Development a - build of a complete Bootstrap 4 page: cloning Newsweek homepage

### PR DESCRIPTION
**Pull request by maosan132**
A project made with Bootstrap v4, taking as an example, I wanted to mimic the Newsweek homepage, so I can avoid legal issues I didn´t take real images from the site, and just use placeholder.it for such purpose. I kindly ask for any feedback for making this work better, towards its approval.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @maosan132, congratulations on building a beautiful and responsive app 👍. Great use of bootstrap classes. To improve on our project we need to make a few changes. Find comments below:
* Kindly edit the PR so it has a beautiful title of the project and also a short description of the project
md
* Kindly ```hide``` the main nav links when scrolling so it looks like the original. Currently
mdn
```Original version```
mdn1
*  Kindly add ```hover``` effects to the ```footer links``` and ```social icons```
* ```Medium screen```
   - ```Social icons``` break on a medium screen. Currently
mdicons
  ```Original version```
mdicons1
  - ```Latest news``` Let us fix the position of the header in the latest news section. Currently 
mdln
  - ```US``` section, currently the layout needs to be fixed
mdus
```Original version```
mdus1

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @maosan132       
#### Great Job so far, working on all requirements stipulated by previous TSE, except one.

### Navigation bar
- [ ] One nav bar should be used for the navigation :you have one normal navbar and you have a fixed nav bar behide it. Kindly note ***Everything should be one Navbar like the original***, lets fix that.



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @maosan132, congratulations on a great job 👍 Well done 🙂 . Based on the fix from previous TSE's, I, therefore, approve of your project. But before we merge to master, there is 1 thing to note before merging: 
* There is a horizontal scroll on both medium and small screen

Once you are done with this change, you can go ahead and merge to master 👍 
Good luck with your next projects 👐 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by maosan132** [comment]
All errors checked and passed, TSE approved the project, so I am merging to master!

**Pull request merged**
